[package]
name = "rust-shape-drawing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.12.0"
simple_logger = "4.2.0"
egui_speedy2d = "0.4.0"
egui = "0.21.0"
rfd = "0.12.0"
